### PR TITLE
fix: tempFile not excluded from exception scan 

### LINKED ISSUE #122: Exclude field does't truly exclude manifest file from vet scan
Hi Team, 

As the title suggests, upon setting the exclude field in vet action - with manifest file paths, some file(s) are stil scanned. Not sure if the config is missing something. Please refer to the image attached:

Image

Thank you.

### PR DESCRIPTION
**Pull request by KunalSin9h**
fixes #122

### CODE REVIEW

File: src/vet.ts [hunk 1]
```diff
@@ -244,6 +245,27 @@ export class Vet {
     }
 
     for (const file of changedLockFiles) {
+      // Checkif filepath to be excluded, if so then skip processing the exceptions list
+      core.info(`Check filepath for exclution patterns: ${file.filename}`)
```
Comment (abhisek) [inline src/vet.ts:249]:
```suggestion
      core.info(`Checking file path for exclusion patterns: ${file.filename}`)
```

**Comment by KunalSin9h** [comment]
@abhisek Using github default node LTS version as mentioned in their runner docs: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

`node 20.19.5`

**Review by abhisek — APPROVED** [review]
